version: "3.6"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.1"
    volumes :
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - es-net
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.17.1"
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch


volumes:
  esdata:
    
networks:
  es-net:
    driver: bridge
