// <auto-generated />
using System;
using Citrouille.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Citrouille.Data.Migrations
{
    [DbContext(typeof(CollectionDbContext))]
    [Migration("20220505070907_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("CollectionSchema")
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Citrouille.Data.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ThemeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId");

                    b.ToTable("Collections", "CollectionSchema");
                });

            modelBuilder.Entity("Citrouille.Data.Entities.CollectionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("Items", "CollectionSchema");
                });

            modelBuilder.Entity("Citrouille.Data.Entities.CollectionTag", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("char(36)");

                    b.HasKey("CollectionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("CollectionTags", "CollectionSchema");
                });

            modelBuilder.Entity("Citrouille.Data.Entities.CollectionTheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Theme")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CollectionTheme", "CollectionSchema");
                });

            modelBuilder.Entity("Citrouille.Data.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tag", "CollectionSchema");
                });

            modelBuilder.Entity("Citrouille.Data.Entities.Collection", b =>
                {
                    b.HasOne("Citrouille.Data.Entities.CollectionTheme", "Theme")
                        .WithMany("Collections")
                        .HasForeignKey("ThemeId");

                    b.OwnsMany("Citrouille.Data.Entities.FieldTemplate", "Fields", b1 =>
                        {
                            b1.Property<Guid>("CollectionId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext");

                            b1.Property<string>("Type")
                                .HasColumnType("longtext");

                            b1.HasKey("CollectionId", "Id");

                            b1.ToTable("FieldTemplate", "CollectionSchema");

                            b1.WithOwner()
                                .HasForeignKey("CollectionId");
                        });

                    b.Navigation("Fields");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Citrouille.Data.Entities.CollectionItem", b =>
                {
                    b.HasOne("Citrouille.Data.Entities.Collection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId");

                    b.OwnsMany("Citrouille.Data.Entities.Field", "Fields", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext");

                            b1.Property<string>("Type")
                                .HasColumnType("longtext");

                            b1.Property<string>("Value")
                                .HasColumnType("longtext");

                            b1.HasKey("ItemId", "Id");

                            b1.ToTable("Field", "CollectionSchema");

                            b1.WithOwner("Item")
                                .HasForeignKey("ItemId");

                            b1.Navigation("Item");
                        });

                    b.Navigation("Collection");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Citrouille.Data.Entities.CollectionTag", b =>
                {
                    b.HasOne("Citrouille.Data.Entities.Collection", "Collection")
                        .WithMany("Tags")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Citrouille.Data.Entities.Tag", "Tag")
                        .WithMany("Collections")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Citrouille.Data.Entities.Collection", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Citrouille.Data.Entities.CollectionTheme", b =>
                {
                    b.Navigation("Collections");
                });

            modelBuilder.Entity("Citrouille.Data.Entities.Tag", b =>
                {
                    b.Navigation("Collections");
                });
#pragma warning restore 612, 618
        }
    }
}
